services:

  model-service:
    image: ${MODEL_IMAGE}
    container_name: model-service
    restart: unless-stopped
    expose:
      - "${SERVER_PORT:-8081}"
    environment:
      SERVER_PORT: "${SERVER_PORT:-8081}"
      MODEL_DIR: /app/output
      MODEL_URL: "${MODEL_URL}"
      PREPROCESSOR_URL: "${PREPROCESSOR_URL}"

    # Without this, the model-service would always download 
    # since output would be empty.
    volumes:
      - ../model-service/output:/app/output
  app:
    image: ${APP_IMAGE}
    container_name: app
    restart: unless-stopped
    ports:
      - "${APP_HOST_PORT:-8080}:8080"
    depends_on:
      - model-service
    environment:
      MODEL_HOST: "${MODEL_HOST:-http://model-service:8081}"