{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.istio.app.virtualService.name }}
spec:
  gateways:
  - {{ .Values.istio.gateway.name }}
  hosts:
    {{- toYaml .Values.istio.app.virtualService.hosts | nindent 4 }}
  http:
  # Canary users (sticky): if header matches, always route to v2
  - match:
    - uri:
        prefix: /
      headers:
        {{ .Values.istio.app.sticky.headerName }}:
          regex: {{ .Values.istio.app.sticky.canaryUserRegex | quote }}
    route:
    - destination:
        host: {{ include "project-app.fullname" . }}-frontend
        subset: v2
    headers:
      response:
        add:
          x-routed-version: "v2"
  # Default users: always route to v1
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ include "project-app.fullname" . }}-frontend
        subset: v1
    headers:
      response:
        add:
          x-routed-version: "v1"
{{- end }}