{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.istio.app.virtualService.name }}
spec:
  gateways:
  - {{ .Values.istio.gateway.name }}
  hosts:
    {{- toYaml .Values.istio.app.virtualService.hosts | nindent 4 }}
  http:

  # - If the request already has the cookie, route 100% to the pinned subset.
  # - Otherwise do a 90/10 split and set the cookie based on which route was taken.
  - name: pinned-canary
    match:
    - uri:
        prefix: /
      headers:
        cookie:
          regex: {{ printf ".*%s=v2.*" .Values.istio.app.canary.cookieName | quote }}
    route:
    - destination:
        host: {{ include "project-app.fullname" . }}-frontend
        subset: v2
    headers:
      response:
        add:
          x-routed-version: "v2"

  - name: pinned-stable
    match:
    - uri:
        prefix: /
      headers:
        cookie:
          regex: {{ printf ".*%s=v1.*" .Values.istio.app.canary.cookieName | quote }}
    route:
    - destination:
        host: {{ include "project-app.fullname" . }}-frontend
        subset: v1
    headers:
      response:
        add:
          x-routed-version: "v1"

  - name: first-time-assignment
    match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ include "project-app.fullname" . }}-frontend
        subset: v1
      weight: {{ .Values.istio.app.weights.v1 }}
      headers:
        response:
          add:
            set-cookie: {{ printf "%s=v1; Path=%s; Max-Age=%d" .Values.istio.app.canary.cookieName .Values.istio.app.canary.cookiePath (int .Values.istio.app.canary.ttlSeconds) | quote }}
            x-routed-version: "v1"
    - destination:
        host: {{ include "project-app.fullname" . }}-frontend
        subset: v2
      weight: {{ .Values.istio.app.weights.v2 }}
      headers:
        response:
          add:
            set-cookie: {{ printf "%s=v2; Path=%s; Max-Age=%d" .Values.istio.app.canary.cookieName .Values.istio.app.canary.cookiePath (int .Values.istio.app.canary.ttlSeconds) | quote }}
            x-routed-version: "v2"
{{- end }}