{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: model-service-dr
spec:
  host: {{ tpl (.Values.istio.modelService.destinationRule.host | toString) . }}
  subsets:
  {{- toYaml .Values.istio.modelService.destinationRule.subsets | nindent 2 }}
{{- end }}