{{- if .Values.modelService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "project-app.fullname" . }}-model-v1
  labels:
    app: {{ include "project-app.fullname" . }}
    component: model
spec:
  replicas: {{ .Values.modelService.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "project-app.fullname" . }}-model
      version: v1
  template:
    metadata:
      labels:
        app: {{ include "project-app.fullname" . }}-model
        component: model
        version: v1
    spec:
      containers:
      - name: model-service
        image: "{{ .Values.modelService.image.repository }}:{{ .Values.modelService.versions.v1.image.tag }}"
        imagePullPolicy: {{ .Values.modelService.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.modelService.service.port }}
        env:
          - name: MODEL_DIR
            valueFrom:
              configMapKeyRef:
                name: {{ include "project-app.fullname" . }}-config
                key: MODEL_DIR
          - name: MODEL_URL
            valueFrom:
              configMapKeyRef:
                name: {{ include "project-app.fullname" . }}-config
                key: MODEL_URL
          - name: PREPROCESSOR_URL
            valueFrom:
              configMapKeyRef:
                name: {{ include "project-app.fullname" . }}-config
                key: PREPROCESSOR_URL
          - name: SERVER_PORT
            value: "{{ .Values.modelService.service.port }}"
        volumeMounts:
        - name: model-volume
          mountPath: {{ .Values.modelService.mountPath }}
      volumes:
      - name: model-volume
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: "{{ if .Values.persistence.claimName }}{{ .Values.persistence.claimName }}{{ else }}{{ include "project-app.fullname" . }}-pvc{{ end }}"
        {{- else }}
        emptyDir: {}
        {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "project-app.fullname" . }}-model-v2
  labels:
    app: {{ include "project-app.fullname" . }}
    component: model
spec:
  replicas: {{ .Values.modelService.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "project-app.fullname" . }}-model
      version: v2
  template:
    metadata:
      labels:
        app: {{ include "project-app.fullname" . }}-model
        component: model
        version: v2
    spec:
      containers:
      - name: model-service
        image: "{{ .Values.modelService.image.repository }}:{{ .Values.modelService.versions.v2.image.tag }}"
        imagePullPolicy: {{ .Values.modelService.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.modelService.service.port }}
        env:
          - name: MODEL_DIR
            valueFrom:
              configMapKeyRef:
                name: {{ include "project-app.fullname" . }}-config
                key: MODEL_DIR
          - name: MODEL_URL
            valueFrom:
              configMapKeyRef:
                name: {{ include "project-app.fullname" . }}-config
                key: MODEL_URL
          - name: PREPROCESSOR_URL
            valueFrom:
              configMapKeyRef:
                name: {{ include "project-app.fullname" . }}-config
                key: PREPROCESSOR_URL
          - name: SERVER_PORT
            value: "{{ .Values.modelService.service.port }}"
        volumeMounts:
        - name: model-volume
          mountPath: {{ .Values.modelService.mountPath }}
      volumes:
      - name: model-volume
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: "{{ if .Values.persistence.claimName }}{{ .Values.persistence.claimName }}{{ else }}{{ include "project-app.fullname" . }}-pvc{{ end }}"
        {{- else }}
        emptyDir: {}
        {{- end }}
{{- end }}
